---
version: "2.1"
services:
    syncthing:
    image: linuxserver/syncthing
    container_name: syncthing
    hostname: syncthing #optional
    network_mode: host
    environment:
        - PUID=1000
        - PGID=1000
        - TZ=US/Pacific
    volumes:
        - /srv/dev-disk-by-id-md-name-raspberrypi-0/syncthing-config:/config
        - /srv/dev-disk-by-id-md-name-raspberrypi-0/media:/data1
    ports:
        - 8384:8384
        - 22000:22000
        - 21027:21027/udp
    restart: unless-stopped